export const usersState$ = (state) => state.users
export const userLoginState$ = (state) => state.userLogin
export const coursesState$ = (state) => state.courses
export const courseDetailsState$ = (state) => state.courseDetails
export const courseLessonState$ = (state) => state.courseLesson
export const studentCourseState$ = (state) => state.studentCourse
export const userProfileState$ = (state) => state.userProfile
export const commentsState$ = (state) => state.comments
export const reviewsState$ = (state) => state.reviews
export const coursesMyState$ = (state) => state.coursesMy
export const studentsInCourseState$ = (state) => state.studentsInCourse
